services:
    db:
        image: postgres:11.13
        container_name: taskList-postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - C:/Work/dockerDB/taskList-postgres/var/lib/postgres
#    pgadmin:
#        image: dpage/pgadmin4
#        container_name: taskList-pgadmin
#        restart: always
#        ports:
#            - "8080:80"
#        depends_on:
#            - db
#        environment:
#            SPRING_DATASOURCE_USERNAME : postgres
#            SPRING_DATASOURCE_PASSWORD : postgres
#
#    taskList:
#        image: taskList-0.0.1-SNAPSHOT
#        container_name: taskList-app
#            build:
#                context:
#                    dockerfile: Dockerfile
#        ports:
#            - "8082:8082"
#        restart: always
#        depends_on:
#            - db
#        environment:
#            SPRING_DATASOURCE_URL: jdbc:postgresql://taskList-postgres:5432/taskListDB?createDatabaseIfNotExist=true
#            SPRING_DATASOURCE_USERNAME: postgres
#            SPRING_DATASOURCE_PASSWORD: postgres

    