services:
    db:
        image: postgres:11.13
        container_name: taskList-postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - C:/Work/dockerDB/taskList-postgres/var/lib/postgres

    